collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5919056
  brandStrength: 1
  rhythmicContrast: 1
  brandColors:
    - '#073146'
    - '#EBFAFF'
    - '#000000'
    - '#A4BCC6'
    - '#11B0F7'
  lightness: 0.7596965
typography_spectrum: 0.7048904
layout_spectrum: 0.4772344
name: Thepixelsilo
